# Generated by Django 3.1.14 on 2024-08-06 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
