# Generated by Django 5.1 on 2024-08-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
