# Generated by Django 5.1 on 2024-09-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_remove_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_description',
            field=models.ImageField(blank=True, null=True, upload_to='plants/description'),
        ),
    ]
