# Generated by Django 5.1 on 2024-09-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_plant_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='salma', max_length=150),
        ),
    ]
