# Generated by Django 5.1 on 2024-09-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_alter_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
