# Generated by Django 5.1 on 2024-08-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='plant',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
